name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug secret
        run: |
          echo "Length: ${#EC2_USER}"
          echo -n "$EC2_USER" | od -c | head -5
        env:
          EC2_USER: ${{ secrets.EC2_USER }}

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/quickbite_deploy
          chmod 600 ~/.ssh/quickbite_deploy

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/quickbite_deploy -o IdentitiesOnly=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} bash -se << "EOF"
            echo "Deployment started!"
            echo "logged in as $(whoami)"
            echo "HOME is: $HOME"
            pwd
            cd ~/quickbite-api
            git pull origin main
            docker compose up -d --build
          EOF
